mvcEFprototype/Controllers/AccountsController.cs
using mvcEFprototype.Filters;
using mvcEFprototype.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvcEFprototype.Controllers
{

    [CustomLog]
    public class AccountsController : Controller
    {
        // GET: Accounts/Login
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        // POST: Accounts
        [HttpPost]
        public ActionResult Login(Account account)
        {
            if (!ModelState.IsValid)
            { 
                return View(); 
            }
            else
            {
                if (account.UserName == "Test" && account.Password == "Test")
                {
                    Session["UserId"] = Guid.NewGuid();//Setting User session
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid login attempt");
                    return View(account);
                }
            }
        }

        public ActionResult Logout()
        {
            HttpContext.Session.Remove("UserId");
            return RedirectToAction("Login");
        }
    }
}

mvcEFprototype/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using mvcEFprototype.Models;
using mvcEFprototype.Service;
using System.IO;
using mvcEFprototype.Filters;

namespace mvcEFprototype.Controllers
{
    [UserAuthenticationFilter]
    [CustomLog]
    public class EmployeesController : Controller
    {
        private IEmployeeService _employee_Service = null;
        public EmployeesController()
        {
            this._employee_Service = new EmployeeService();
        }
        public EmployeesController(EmployeeService Service)
        {
            this._employee_Service = Service;
        }

        // GET: Employees
        public async Task<ActionResult> Index()
        {   
             return View(await _employee_Service.GetAll());
        }

        // GET: Employees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                // return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                throw(new Exception("This employee does not exist"));
            }
            Employee employee = _employee_Service.GetById(id);
            if (employee == null)
            {
                // return HttpNotFound();
                throw (new Exception("This employee does not exist"));
            }
            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(/**[Bind(Include = "Id,FirstName,LastName,Age,Position,Office,Salary")]**/ Employee employee)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var binaryReader = new BinaryReader(Request.Files[0].InputStream))
                    {
                        employee.UploadFile = binaryReader.ReadBytes(Request.Files[0].ContentLength);
                        employee.UploadFilename = Request.Files[0].FileName;
                    }
                    _employee_Service.Insert(employee);
                    _employee_Service.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                throw (new Exception("Something is wrong"));
            }
            return View(employee);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                throw (new Exception("This employee does not exist."));
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = _employee_Service.GetById(id);
            if (employee == null)
            {
                // return HttpNotFound();
                throw (new Exception("This employee does not exist."));
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(/**[Bind(Include = "Id,FirstName,LastName,Age,Position,Office,Salary")]***/ Employee employee)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (var binaryReader = new BinaryReader(Request.Files[0].InputStream))
                    {
                        if (Request.Files[0].ContentLength != 0 && Request.Files[0].FileName.Length != 0)
                        {
                            employee.UploadFile = binaryReader.ReadBytes(Request.Files[0].ContentLength);
                            employee.UploadFilename = Request.Files[0].FileName;
                        }

                    }
                    _employee_Service.Update(employee);
                    _employee_Service.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                throw (new Exception("Something is wrong."));
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int? id)
        {
            Employee employee = null;
            try
            {
                if (id == null)
                {
                    throw (new Exception("This employee does not exist."));
                    // return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                employee = _employee_Service.GetById(id);
                if (employee == null)
                {
                    throw (new Exception("This employee does not exist."));
                    // return HttpNotFound();
                }
            }
            catch (Exception e)
            {

            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                _employee_Service.Delete(id);
                _employee_Service.Save();
            }
            catch (Exception e)
            {
                throw (new Exception("Something is wrong."));
            }
            return RedirectToAction("Index");
        }

        public FileResult DownloadFile(int id)
        {
            return File(_employee_Service.GetById(id).UploadFile, System.Net.Mime.MediaTypeNames.Application.Octet, _employee_Service.GetById(id).UploadFilename);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _employee_Service.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

mvcEFprototype/Views/Shared/CustomErrorsException.cshtml
<!DOCTYPE html>
@{
    ViewBag.Title = "CustomErrorsException";
}
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/semantic")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <h2>SomeException</h2>
    <div class="title">
        <div class="ui error message" style="width:50%">
            Error.<br>
            Some thing when Wrong kindly check after few hours
        </div>
    </div>
</body>

</html>

mvcEFprototype/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/semantic")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="ui pushable " style="transform:none">
        @*Add Side Bar*@
        <div class="ui visible inverted left vertical sidebar menu   ">
            <a class="item" href="@Url.Action("Index", "Home")">
                <i class="home icon"></i>
                Home
            </a>
            <a class="item">
                <i class="block layout icon"></i>
                Topics
            </a>
            <a class="item" href="@Url.Action( "Index", "Employees")">
                <i class="smile icon"></i>
                Employees
            </a>
            @if (HttpContext.Current.Session["UserId"] is null)
            {
                <a class="item" href="@Url.Action("Login","Accounts")">
                    <i class="calendar icon"></i>
                    Login
                </a>
            }
            else
            {
                <a class="item" href="@Url.Action("Logout","Accounts")">
                    <i class="calendar icon"></i>
                    Logout
                </a>
            }

        </div>
        <div class="pusher content" style="width:calc(100%-250px)">
            <div class="ui basic ">
                @RenderBody()
            </div>
        </div>

    </div>
    <div class="">
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>



    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @Scripts.Render("~/bundles/semantic")
    @Scripts.Render("~/bundles/custom")
    @RenderSection("scripts", required: false)
</body>
</html>

mvcEFprototype/Views/Shared/_Layout_back.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="container-fluid">
            <div class="nav navbar-nav navbar-right">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Employees profile", "Index", "Employees")</li>
                </ul>
            </div>
        </div>
    </div>
    @*<div class="navbar navbar-inverse navbar-fixed-top ">*@
    <div class="container-fluid">
        <div class=" row">
            <div class="col-md-2">

                @*<div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                             <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                            <li>@Html.ActionLink("Employees", "Index", "Employees")</li>
                        </ul>
                    </div>*@

                <ul class="nav nav-pills nav-stacked ">
                    <li role="presentation" class="active">@Html.ActionLink("Home", "Index", "Home") </li>
                    <li role="presentation" class="active">@Html.ActionLink("Employees", "Index", "Employees")</li>
                    <li role="presentation" class="active"><a href="#">Messages</a></li>
                </ul>
            </div>
            <div></div>
            <div class="col-md-10">
                <div class="body-content container-fluid">
                    @RenderBody()
                    <hr />
                    <footer>
                        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
                    </footer>
                </div>
            </div>
        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </div>
</body>
</html>